apiVersion : apps/v1
kind: Deployment
metadata:
  name: m 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m
  template:
    metadata:
      labels:
        app: m 
    spec:
      containers:
        - name: m 
          image: myacrchandu.azurecr.io/m
          ports:
          - containerPort: 8080